version: "2"
services:
  test-python:
    image: test-truck:latest
    build:
      context: ./populate-db
      dockerfile: ./Dockerfile
    depends_on:
    - db
  db:
    image: postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d