version: "2"
services:
  food-truck-db:
    container_name: db
    image: postgis/postgis
    environment:
      - POSTGRESQL_INITSCRIPTS_USERNAME=postgres
      - POSTGRESQL_INITSCRIPTS_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres/data:/data
      - ./postgres/init:/docker-entrypoint-initdb.d
  food-truck-api:
    container_name: food-truck-api
    image: food-truck-api:latest
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
